groups:
- name: ping
  rules:

  - alert: InstanceDown
    expr: ping_result_code > 0
    for: 5m
    labels:
        severity: page
    annotations:
        summary: "Instance {{ $labels.url }} down"
        description: "{{ $labels.url }} of job {{ $labels.job }} has been down for more than 5 minutes."
