FROM telegraf:1.18.0
COPY ./files/IANAifType-MIB.txt /usr/share/snmp/mibs
COPY ./files/IF-MIB.txt /usr/share/snmp/mibs
COPY ./files/RFC1213-MIB.txt /usr/share/snmp/mibs
COPY ./files/SNMPv2-CONF.txt /usr/share/snmp/mibs
COPY ./files/SNMPv2-MIB.txt /usr/share/snmp/mibs
COPY ./files/SNMPv2-SMI.txt /usr/share/snmp/mibs
COPY ./files/SNMPv2-TC.txt /usr/share/snmp/mibs
COPY ./files/UBNT-MIB /usr/share/snmp/mibs
COPY ./files/UBNT-UniFi-MIB /usr/share/snmp/mibs